### ISSUE TITLE
Add a benchmark harness

### ISSUE THREAD

**Issue by kddnewton** [kddnewton/regular_expression#15]
We should have a benchmark harness that we can run in this repository to compare against latest Ruby. It should include various test cases against different constructs (grouping, repetition, alternation, etc). It should test against very small and very large strings. It should include some kind of nice output format.

**Comment by noahgibbs** [comment]
@chrisseaton suggests trying some regexps from https://github.com/Shopify/browser_sniffer/blob/master/lib/browser_sniffer/patterns.rb

**Comment by noahgibbs** [comment]
Okay, I have a basic harness in a branch (bench_harness). Now I just need to add a bunch of regexps to benchmark :-)

**Comment by kddnewton** [comment]
This is now working! Thanks @noahgibbs
