### ISSUE TITLE
Run against RubySpec

### ISSUE THREAD

**Issue by chrisseaton** [kddnewton/regular_expression#18]
Try monkey-patching Ruby's builtin regular expressions to use this library instead, then see how much of RubySpec https://github.com/ruby/spec/tree/master/language/regexp we can pass like this.

**Comment by Schwad** [comment]
Would the idea be to

* Build our own ruby fork (in another repo?) updated to use this library
* Dry run locally against specs
* When passes, maybe add this as a github action in CI? (or maybe have it as an optional run on all PRs so we can see how close we're getting to feature parity)?
