### ISSUE TITLE
Come up with a better name for this gem

### ISSUE THREAD

**Issue by kddnewton** [kddnewton/regular_expression#22]

**Comment by chrisseaton** [comment]
* Rextra
* IrregularExpression

**Comment by kddnewton** [comment]
I actually wanted IrregularExpression but didn't want to imply we supported non-regular languages...

**Comment by tomstuart** [comment]
regex86

**Comment by chrisseaton** [comment]
`x86` sounds a bit retro to me - I'd normally only use that term for 32-bit architectures.

**Comment by noahgibbs** [comment]
rregex2000 :-P

**Comment by jbourassa** [comment]
Fregex => Fast ruby|regular expressions

**Comment by Schwad** [comment]
Sometimes you can just grab a namespace that has nothing to do with the problem area and claim that land as your own. (e.g. Capybara, Hpricot, Trucker)

so....

* `snowy_owl`
* `jerboa`
