### ISSUE TITLE
Basic benchmarking

### ISSUE THREAD

**Issue by noahgibbs** [kddnewton/regular_expression#30]
I'll put together a very simple benchmarking suite for this. It would be nice to know the performance of this compared to (e.g.) Ruby built-in regexps, and to track speed over time. We can also include intentional pathological cases and see if we can fix them.

**Comment by chrisseaton** [comment]
Maybe try some regular expressions from https://github.com/Shopify/browser_sniffer/blob/master/lib/browser_sniffer/patterns.rb.

**Comment by noahgibbs** [comment]
Oh hey, this is a dup of #15.
